openapi: 3.0.1
info:
  title: Moyoy API Server
  description: Moyoy API Server description
  version: v1.0.0
servers:
- url: https://api.moyoy.shop
  description: prod
- url: http://localhost:8080
  description: local
tags: []
paths:
  /api/v1/auth/reissue/token:
    post:
      tags:
      - ğŸ”„ JWT ì¬ë°œê¸‰
      summary: "JWT ì¬ë°œê¸‰ ì‹¤íŒ¨ ì¼€ì´ìŠ¤: ì¸ì¦ í—¤ë”ë‚˜ ì¿ í‚¤ì— JWT í† í°ì´ ì¡´ì¬ í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
      description: "JWT ì¬ë°œê¸‰ ì‹¤íŒ¨ ì¼€ì´ìŠ¤: ì¸ì¦ í—¤ë”ë‚˜ ì¿ í‚¤ì— JWT í† í°ì´ ì¡´ì¬ í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤."
      operationId: JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_1JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_2JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_3JWT
        ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_4JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_5jwt-reissue-success
      responses:
        "401":
          description: "401"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-auth-reissue-token1690395706'
              examples:
                JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_1:
                  value: "{\"status\":401,\"code\":\"LOGIN_401_1\",\"message\":\"ì¸\
                    ì¦ í—¤ë”ë‚˜ ì¿ í‚¤ì— JWT í† í°ì´ ì¡´ì¬ í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.\",\"data\":null}"
                JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_2:
                  value: "{\"status\":401,\"code\":\"LOGIN_401_2\",\"message\":\"í† \
                    í° íƒ€ì…ì´ ì˜¬ë°”ë¥´ì§€ ì•ŠìŠµë‹ˆë‹¤.\",\"data\":null}"
                JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_3:
                  value: "{\"status\":401,\"code\":\"LOGIN_401_3\",\"message\":\"ìœ \
                    íš¨í•˜ì§€ ì•Šì€ í† í°ì…ë‹ˆë‹¤.\",\"data\":null}"
                JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_4:
                  value: "{\"status\":401,\"code\":\"LOGIN_401_4\",\"message\":\"ë§Œ\
                    ë£Œëœ í† í°ì…ë‹ˆë‹¤.\",\"data\":null}"
                JWT ì¬ë°œê¸‰ ì‹¤íŒ¨-LOGIN_401_5:
                  value: "{\"status\":401,\"code\":\"LOGIN_401_5\",\"message\":\"ë¸”\
                    ë™ë¦¬ìŠ¤íŠ¸ ì²˜ë¦¬ëœ í† í° ì…ë‹ˆë‹¤.\",\"data\":null}"
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-v1-auth-reissue-token-677170853'
              examples:
                jwt-reissue-success:
                  value: "{\"status\":200,\"code\":\"OK\",\"message\":null,\"data\"\
                    :{\"accessToken\":\"reissued-access-token\"}}"
components:
  schemas:
    api-v1-auth-reissue-token-677170853:
      required:
      - code
      - message
      - status
      type: object
      properties:
        code:
          type: string
          description: ì„±ê³µ/ì—ëŸ¬ ì½”ë“œ
        data:
          required:
          - accessToken
          type: object
          properties:
            accessToken:
              type: string
              description: ìƒˆë¡œ ë°œê¸‰ëœ Access Token
        status:
          type: number
          description: ì‘ë‹µ ìƒíƒœ
    api-v1-auth-reissue-token1690395706:
      required:
      - code
      - message
      - status
      type: object
      properties:
        code:
          type: string
          description: ì—ëŸ¬ ì½”ë“œ (LOGIN_401_5)
        message:
          type: string
          description: ì—ëŸ¬ ë©”ì‹œì§€
        status:
          type: number
          description: ì‘ë‹µ ìƒíƒœ
